name: trpc_client
description: A minimal trpc client for Dart and Flutter.
version: 0.3.4
repository: https://github.com/wosherco/trpc-client-dart
issue_tracker: https://github.com/wosherco/trpc-client-dart/issues
homepage: https://github.com/wosherco/trpc-client-dart

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.1
  queue: ^3.1.0+2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
